Исключения в Java (Java Exception)
<p>----------------------------------------</p>
В повседневной жизни иногда возникают ситуации, которые мы не планировали. Например, встаешь утром на работу, ищешь зарядное устройство к телефону — а его нет. Идешь в ванную, чтобы умыться – отключили воду. Сел в машину – не заводится. Но человек ...
<p>----------------------------------------</p>
В повседневной жизни иногда возникают ситуации, которые мы не планировали. Например, встаешь утром на работу, ищешь зарядное устройство к телефону — а его нет. Идешь в ванную, чтобы умыться – отключили воду. Сел в машину – не заводится. Но человек в состоянии довольно легко справиться с такими непредвиденными ситуациями. А как с ними справляются Java-программы, постараемся разобраться в этой статье. <h2>Что такое исключения (exceptions java)</h2>В мире программирования возникновение ошибок и непредвиденных ситуаций при выполнении программы называют исключением (exception). В программе исключения могут возникать в результате неправильных действий пользователя, отсутствии необходимого ресурса на диске, или потери соединения с сервером по сети. 

Причинами исключений при выполнении программы также могут быть ошибки программирования или неправильное использование API. В отличие от нашего мира, программа должна четко знать, как поступать в такой ситуации. Для этого в Java предусмотрен механизм исключений. 
<h2>Кратко о ключевых словах try, catch, finally, throws</h2>Обработка исключений в Java основана на использовании в программе следующих ключевых слов:
<ul>
<li>try – определяет блок кода, в котором может произойти исключение;</li> 
<li>catch – определяет блок кода, в котором происходит обработка исключения;</li>
<li>finally – определяет блок кода, который является необязательным, но при его наличии выполняется в любом случае независимо от результатов выполнения блока try.</li>
</ul>Эти ключевые слова используются для создания в программном коде специальных обрабатывающих конструкций: try{}catch, try{}catch{}finally, try{}finally{}.
<ul>
<li>throw – используется для возбуждения исключения;</li>
<li>throws – используется в сигнатуре методов для предупреждения, о том что метод может выбросить исключение.</li>
</ul>Пример использования ключевых слов в Java-программе:

<pre class="lang-java line-numbers"><code>
//метод считывает строку с клавиатуры

public String input() throws MyException {//предупреждаем с помощью throws, 
// что метод может выбросить исключение MyException
      BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
    String s = null;
//в блок try заключаем код, в котором может произойти исключение, в данном
// случае компилятор нам подсказывает, что метод readLine() класса 
// BufferedReader может выбросить исключение ввода/вывода
    try {
        s = reader.readLine();
// в блок  catch заключаем код по обработке исключения IOException  
    } catch (IOException e) {
        System.out.println(e.getMessage());
// в блоке finally закрываем поток чтения
    } finally {
// при закрытии потока тоже возможно исключение, например, если он не был открыт, поэтому “оборачиваем” код в блок try
        try {
            reader.close();
// пишем обработку исключения при закрытии потока чтения
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    if (s.equals("")) {
// мы решили, что пустая строка может нарушить в дальнейшем работу нашей программы, например, на результате этого метода нам надо вызывать метод substring(1,2), поэтому мы вынуждены прервать выполнение программы с генерацией своего типа исключения MyException с помощью throw
        throw new MyException("String can not be empty!");
    }
    return s;
}
</code></pre><h2>Для чего нужен механизм исключений?</h2>Посмотрим на пример из реального мира. Представьте, что на автомобильной дороге есть участок с аварийным мостом с ограниченной грузоподъемностью. Если по нему поедет автомобиль с массой, превышающей грузоподъемность моста, он может разрушиться, и ситуация для водителя может стать, мягко говоря, исключительной.

Чтобы этого не произошло, дорожная служба заблаговременно устанавливает предупредительные знаки на дороге. 

Водитель автомобиля, глядя на предупреждающий знак, будет сравнивать массу своего автомобиля с разрешенной для проезда по мосту. Если она превышает ее – он поедет по объездному пути. 

Благодаря действиям дорожной службы водители грузового транспорта, во-первых, получили возможность заблаговременно изменять свой путь, во-вторых, предупреждены об опасности на основном пути, и, наконец, предупреждены о невозможности использования моста при определенных условиях.
<div class="row justify-content-center jr-image-wrap"><div class="col-12 col-sm-10 col-md-8"><img data-id="9943b02d-8a5c-4278-8472-09a4ed14eaed" data-max-width="710" alt="Исключения в Java - 2" src="https://cdn.javarush.com/images/article/9943b02d-8a5c-4278-8472-09a4ed14eaed/1024.jpeg"></div></div>Возможность предупреждения и разрешения исключительной ситуации в программе для ее продолжения – одна из причин использования исключений в Java. Механизм исключений также позволяет защитить написанный вами код (программный интерфейс) от неправильного использования пользователем за счет валидации (проверки) входящих данных.

Давайте теперь на секунду побудем дорожной службой. Во-первых, вы должны знать места, где автомобилистов могут ждать неприятности. Во-вторых, вам нужно заготовить и установить предупредительные знаки. И, наконец, вам нужно предусмотреть объездные маршруты в случае опасности на основном пути. 

В Java механизм исключений работает похожим образом. На стадии разработки программы мы «ограждаем» опасные участки кода в отношении исключений с помощью блока try{}, предусматриваем «запасные» пути с помощью блока catch{}, в блоке finally{} мы пишем код, который выполняется в программе при любом исходе.

В случаях, когда мы не можем  предусмотреть «запасной путь» или намеренно хотим предоставить право его выбора пользователю, мы должны, по крайней мере, предупредить его об опасности. Почему? А вы только вообразите негодование водителя, который доедет до аварийного моста, по которому нельзя проехать, не встретив по дороге ни одного предупреждающего знака! 

В программировании при написании своих классов и методов мы не всегда можем предвидеть контекст их использования другими разработчиками в своих программах, поэтому не можем предвидеть на 100% правильный путь для разрешения  исключительной ситуации. В то же время, правило хорошего тона — предупредить пользователей нашего кода о возможности исключительной ситуации. 

Механизм исключений Java позволяет нам сделать это с помощью throws – по сути, объявления общего поведения нашего метода, заключающееся в выбрасывании исключения, и предоставляя, таким образом, написание кода по обработке исключения в Java пользователю метода.

<div class="email-subscription"><iframe frameborder="0" src="https://secure.esputnik.com.ua/4Q0Ef6d2SOs" width="100%" height="200" scrolling="no"></iframe></div><h2>Предупреждение о «неприятностях»</h2>Когда вы не планируете обрабатывать исключение в своем методе, но хотите предупредить пользователей метода о возможных исключительных ситуациях — используйте ключевое слово throws. Это ключевое слово в сигнатуре метода означает, что при определенных условиях метод, может выбросить исключение. 

Такое предупреждение является частью интерфейса метода и предоставляет право пользователю на собственный вариант реализации обработчика исключения.

После throws мы указываем тип выбрасываемого исключения. Обычно это наследники класса <span class="code">Exception</span> Java. Поскольку Java является объектно-ориентированным языком, все исключения в Java представляют собой объекты.
<div class="row justify-content-center jr-image-wrap"><div class="col-12 col-sm-10 col-md-8"><img data-id="8fc76f74-5d07-43a1-a16b-7a4b77b10879" data-max-width="799" alt="Исключения в Java - 3" src="https://cdn.javarush.com/images/article/8fc76f74-5d07-43a1-a16b-7a4b77b10879/1024.jpeg"></div></div><h2>Иерархия исключений Java</h2>При возникновении ошибки в процессе выполнения программы исполняющая среда JVM создает объект нужного типа из иерархии исключений Java – множества возможных исключительных ситуаций, унаследованных от общего «предка» – класса Throwable.

Исключительные ситуации, возникающие в программе, можно разделить на две группы: 
<ol>
<li>Ситуации, при которых восстановление дальнейшей нормальной работы программы невозможно</li>
<li>Восстановление возможно.</li>
</ol>К первой группе относят ситуации, когда возникают исключения, унаследованные из класса <span class="code">Error</span>. Это ошибки, возникающие при выполнении программы в результате сбоя работы JVM, переполнения памяти или сбоя системы. Обычно они свидетельствуют о серьезных проблемах, устранить которые программными средствами невозможно. Такой вид исключений в Java относится к неконтролируемым (unchecked) на стадии компиляции.

К этой группе также относят RuntimeException – исключения, наследники класса <span class="code">Exception</span>, генерируемые  JVM во время выполнения программы. Часто причиной возникновения их являются ошибки программирования. Эти исключения также являются неконтролируемыми (unchecked) на стадии компиляции, поэтому написание кода по их обработке не является обязательным.

Ко второй группе относят исключительные ситуации, предвидимые еще на стадии написания программы, и для которых должен быть написан код обработки. Такие исключения являются контролируемыми (checked). Основная часть работы разработчика на Java при работе с исключениями – обработка таких ситуаций.
<h2>Создание исключения</h2>При исполнении программы исключение генерируется JVM или вручную, с помощью оператора <span class="code">throw</span>. При этом в памяти создается объект исключения и выполнение основного кода программы прерывается, а обработчик исключений JVM пытается найти способ обработать исключение.
<h2>Обработка исключения</h2>Создание блоков кода, для которых мы предусматриваем обработку исключений в Java, производится в программе с помощью конструкций try{}catch, try{}catch{}finally, try{}finally{}.
<div class="row justify-content-center jr-image-wrap"><div class="col-12 col-sm-10 col-md-8"><img data-id="2cb82932-4d46-4565-88a7-73d4d869329b" data-max-width="710" alt="Исключения в Java - 4" src="https://cdn.javarush.com/images/article/2cb82932-4d46-4565-88a7-73d4d869329b/1024.jpeg"></div></div>При возбуждении исключения в блоке try обработчик исключения ищется в следующем за ним блоке catch. Если в catch есть обработчик данного типа исключения – управление переходит к нему. Если нет, то JVM ищет обработчик этого типа исключения в цепочке вызовов методов до тех пор, пока не будет найден подходящий catch. 

После выполнения блока catch управление передается в необязательный блок <span class="code">finally</span>.

В случае, если подходящий блок catch не найден, JVM останавливает выполнение программы, и выводит стек вызовов методов – <span class="code">stack trace</span>, выполнив перед этим код блока finally при его наличии.

Пример обработки исключений:

<pre class="lang-java line-numbers"><code>
public class Print {

     void print(String s) {
        if (s == null) {
            throw new NullPointerException("Exception: s is null!");
        }
        System.out.println("Inside method print: " + s);
    }

    public static void main(String[] args) {
        Print print = new Print();
        List<string> list= Arrays.asList("first step", null, "second step");

        for (String s:list) {
            try {
                print.print(s);
            }
            catch (NullPointerException e) {
                System.out.println(e.getMessage());
                System.out.println("Exception was processed. Program continues");
            }
            finally {
                System.out.println("Inside bloсk finally");
            }
            System.out.println("Go program....");
            System.out.println("-----------------");
        }

    }
    }
</string></code></pre>
Результаты работы метода <span class="code">main</span>:

<pre class="lang-java line-numbers"><code>
Inside method print: first step
Inside bloсk finally
Go program....
-----------------
Exception: s is null!
Exception was processed. Program continues
Inside bloсk finally
Go program....
-----------------
Inside method print: second step
Inside bloсk finally
Go program....
-----------------
</code></pre>
Блок <code>finally</code> обычно используется для того, чтобы закрыть открытые в блоке try потоки или освободить ресурсы. Однако при написании программы не всегда возможно уследить за закрытием всех ресурсов. Для облегчения нашей жизни разработчики Java предложили нам конструкцию <code>try-with-resources</code>, которая автоматически закрывает ресурсы, открытые в блоке try.

Наш первый пример можно переписать так с помощью <code>try-with-resources</code>:

<pre class="lang-java line-numbers"><code>
public String input() throws MyException {
    String s = null;
    try(BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))){
        s = reader.readLine();
   } catch (IOException e) {
       System.out.println(e.getMessage());
   }
    if (s.equals("")){
        throw new MyException ("String can not be empty!");
    }
    return s;
}
</code></pre>
Благодаря возможностям Java, начиная с версии 7, мы также можем объединять перехват разнотипных исключений в одном блоке, делая код более компактным и читабельным. Например:

<pre class="lang-java line-numbers"><code>
public String input() {
    String s = null;
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
        s = reader.readLine();
        if (s.equals("")) {
            throw new MyException("String can not be empty!");
        }
    } catch (IOException | MyException e) {
        System.out.println(e.getMessage());
    }
    return s;
}
</code></pre><h4>Итоги</h4>Использование исключений в Java позволяет повысить отказоустойчивость программы за счет использования «запасных» путей, отделить логику основного кода от кода обработки исключительных  ситуаций за счет использования блоков catch, а также дает нам возможность переложить  обработку исключений на пользователя нашего кода с помощью throws.
<table>
<thead>
<tr>
<th>
Что еще почитать:
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<p><a href="https://javarush.com/groups/posts/895-top-10-voprosov-ob-iskljuchenijakh-v-java" target="_blank">Топ 10 вопросов об исключениях в Java</a></p>
</td>
</tr>
</tbody>
</table>